spring:
  application:
    name: discoveryservice
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: POSTGRESQL
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgresSQLInnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${POSTGRES_DATABASE}
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@${eureka.instance.hostname}:${server.port}/eureka/

    fetch-registry: false             # Ne télécharge pas la liste des services
    register-with-eureka: false       # Ne s'enregistre pas car c'est le serveur lui-même

  server:
    enable-self-preservation: false   # Désactive la protection automatique
    renewal-percent-threshold: 0.33   # Seuil de suppression des services morts
    wait-time-in-ms-when-sync-empty: 0   # Démarrage immédiat même si pas de voisins
    peer-node-read-timeout-ms: 30000     # Timeout entre serveurs Eureka (30 sec)


server:
  port: ${SERVER_PORT}


