ACTIVE_PROFILE: test

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: 192.168.1.106
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letmein
ROLES: EUREKA_CLIENT


SERVER_PORT: 5002
UI_APP_URL: http://localhost:3000