ACTIVE_PROFILE: prod

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: 192.168.1.106
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letmein

SERVER_PORT: 8088

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: quincyaus@gmail.com
EMAIL_PASSWORD: zoduwfetslnxywhi
VERIFY_EMAIL_HOST: http://localhost:3000

UI_APP_URL: http://localhost:3000

JWKS_URI: http://localhost:8080/oauth2/jwks

KAFKA_SERVER_URL: http://192.168.1.106:9092
