ACTIVE_PROFILE: prod

PRIVATE_KEY:
PUBLIC_KEY:

POSTGRES_USERNAME: user
POSTGRES_PASSWORD: letmein
POSTGRES_HOST: 192.168.1.106
POSTGRES_PORT: 5432
POSTGRES_DATABASE: localdb

USER_NAME: admin
PASSWORD: letmein

SERVER_PORT: 8080
UI_APP_URL: http://localhost:3000